name: CI Pipeline
on:
   push:
    branches:
     - main
   pull_request:
    branches:
    - main
jobs:
 build:
  runs-on: ubuntu-latest
  steps:
  - name: Checkout code
    uses: actions/checkout@v3
  - name: Set up Python
    uses: actions/setup-python@v4
    with:
     python-version: '3.13' # spécifiez la version de Python

  - name: Install dependencies
    run: |
     python -m pip install --upgrade pip
     pip install -r requirements.txt # assurez-vous d'avoir ce fichier

  - name: Run tests
    run: |
     pytest # ou toute autre commande pour exécuter vos tests

  - name: Set up Docker
    run: |
     sudo apt-get update
     sudo apt-get install -y docker.io

# Nouvelle étape : Construire l'image Docker
  - name: Build Docker image
    run: |
     docker build -t ${{ secrets.DOCKER_USERNAME }}/flask-app:latest .

# Nouvelle étape : Connexion à Docker Hub
  - name: Log in to Docker Hub
    run: |
     echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

# Nouvelle étape : Pousser l'image Docker sur Docker Hub
  - name: Push Docker image to Docker Hub
    run: |
     docker push ${{ secrets.DOCKER_USERNAME }}/flask-app:latest